name: Eleventy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist