name: Eleventy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Eleventy Action
        uses: TartanLlama/actions-eleventy@v1.2